steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/fastapi-python312-app:latest', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/fastapi-python312-app:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy fastapi-python312-app \
      --image gcr.io/$PROJECT_ID/fastapi-python312-app:latest \
      --platform managed \
      --region us-west2 \
      --allow-unauthenticated

images:
- 'gcr.io/$PROJECT_ID/fastapi-python312-app:latest'
